# .streamlit/secrets.toml
[gcp_service_account]
type = "service_account"
project_id = "crypto-portfolio-123456"
private_key_id = "real-key-id-here"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC...\n-----END PRIVATE KEY-----\n"
client_email = "crypto-service@crypto-portfolio-123456.iam.gserviceaccount.com"
client_id = "123456789012345678901"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/oauth2/v3/certs/crypto-service%40crypto-portfolio-123456.iam.gserviceaccount.com"

SENDGRID_API_KEY = "SG.real-api-key-here"
FROM_EMAIL = "hanhpv.vt@gmail.com"